[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "SERVER_PORT=$PORT npm run start -w @nangohq/nango-server"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

